// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znohucbxvuitqpparsyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpub2h1Y2J4dnVpdHFwcGFyc3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTk1NTMsImV4cCI6MjA1NzE5NTU1M30.YlDfCY2mxPFweLDYNvm8sWnINK1HcZC87p9-NOfUngE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);